### ISSUE TITLE
Getting HTTP 500 Internal Error after adding FCM Service Account File

### ISSUE THREAD

**Issue by victorlsn** [pusher/push-notifications-android#149] opened 2024-06-03 09:50 UTC
After adding the FCM file on our Dashboard, we started receiving information on our Error Tracking:

POST https://{INSTANCE_ID}.pushnotifications.pusher.com/device_api/v1/instances/{DEVICE}/devices/fcm [500]

We have over 23k occurrences of this event in our dashboard, plus notifications aren't currently working.
We'd like to at least remove the Service Account file from the Dashboard for now, but that also doesn't seem to be an option on the Dashboard UI.

**Comment by JonathanCaspar** [comment] 2024-06-28 14:29
I'm having the exact same problem, I'm unable to register any new device for push notifications because of this.

I was trying to set up `Pusher Beams` using `Flutter` but faced the following error in the Android emulator:
> W/PushNotificationsAPI( X): Failed to register device: NOKResponse(error=Something went wrong, description=Device could not be created)

After debugging in `push-notifications-android` library source code, I figured that this error was caused by a HTTP 500 Internal Error returned by 
> POST https://{INSTANCE_ID}.pushnotifications.pusher.com/device_api/v1/instances/{DEVICE}/devices/fcm

when the library executes the `registerFCM` function.

The library calls this endpoint by passing a `token`, a `metadata` object and a`knownPreviousClientIds` list, which seems to be a different signature than the one documented here ([Pusher API documentation#register-new-fcm-device](https://pusher.com/docs/beams/reference/device-api/#register-new-fcm-device)) for this same endpoint.

In the documentation mentioned above, the endpoint for registering to FCM apparently requires a `bundleIdentifier` which the client library doesn't seem to provide to the endpoint.

I tested the same call in Postman by explicitely passing a `bundleIdentifier` but still getting a HTTP 500.

There seems to be an internal issue going on on Pusher Beams API side, could anyone from the Pusher team please have a look at this?

**Comment by andrewindayang** [comment] 2024-07-11 08:21
> I'm having the exact same problem, I'm unable to register any new device for push notifications because of this.
> 
> I was trying to set up `Pusher Beams` using `Flutter` but faced the following error in the Android emulator:
> 
> > W/PushNotificationsAPI( X): Failed to register device: NOKResponse(error=Something went wrong, description=Device could not be created)
> 
> After debugging in `push-notifications-android` library source code, I figured that this error was caused by a HTTP 500 Internal Error returned by
> 
> > POST https://{INSTANCE_ID}.pushnotifications.pusher.com/device_api/v1/instances/{INSTANCE_ID}/devices/fcm
> 
> when the library executes the `registerFCM` function.
> 
> The library calls this endpoint by passing a `token`, a `metadata` object and a`knownPreviousClientIds` list, which seems to be a different signature than the one documented here ([Pusher API documentation#register-new-fcm-device](https://pusher.com/docs/beams/reference/device-api/#register-new-fcm-device)) for this same endpoint.
> 
> In the documentation mentioned above, the endpoint for registering to FCM apparently requires a `bundleIdentifier` which the client library doesn't seem to provide to the endpoint.
> 
> I tested the same call in Postman by explicitely passing a `bundleIdentifier` but still getting a HTTP 500.
> 
> There seems to be an internal issue going on on Pusher Beams API side, could anyone from the Pusher team please have a look at this?

yeah... i ve the same issue too... possible help us with this please..

**Comment by kimonneuhoff** [comment] 2024-10-07 11:22
why is no one looking into this???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? what am i paying for????

**Comment by aonemd** [comment] 2024-12-13 13:00
Hello everyone, this is a duplicate of https://github.com/pusher/push-notifications-android/issues/150, we posted a solution [here](https://github.com/pusher/push-notifications-android/issues/150#issuecomment-2476028019).

**Closed** 2024-12-13 13:00 UTC
